import Vue from 'vue';
import VueI18n from 'vue-i18n';

Vue.use(VueI18n);

const messages = {
    'jp': {
        currentLang: 'ja',
        name: '名前',
        phone: '電話番号',
        gender: '性別',
        email: 'メール',
        homepage: 'ホームページ',
        footer: 'これはフッターゾーンです。',
        navigator: 'これはナビゲーターゾーンです。',
        lookupName: '名前',
        lookupPhone: '電話番号',
        lookupGender: '性別',
        male: '男性',
        female: '女性',
        other: 'その他',
        all: 'すべて',
        birthday: '生日',
        province: '州',
        search: '検索',
        reset: 'リセット',
        hasNoData: 'データなし。',
        itemName: '品名',
        lotNo: 'ロットNo.',
        inventClass: '在庫区分',
        inventClass1: '原反',
        inventClass2: '半製品',
        inventClass3: '試作品',
        weight: '重量',
        coreNo: 'コアNo.',
        location: 'ロケーション',
        rollLength: 'ロール長さ',
        rollWidth: 'ロール幅',
        rollThickness: 'ロール厚み',
        rollWeight: 'ロール重量',
        usage: '用途'
    },
    'en': {
        currentLang: 'en',
        name: 'Name',
        phone: 'Phone',
        gender: 'Gender',
        email: 'Email',
        homepage: 'Homepage',
        footer: 'This is footer zone.',
        navigator: 'This is navigator zone.',
        lookupName: 'Name',
        lookupPhone: 'Phone',
        lookupGender: 'Gender',
        male: 'Male',
        female: 'Female',
        other: 'Other',
        all: 'All',
        birthday: 'Birthday',
        province: 'Province',
        search: 'Search',
        reset: 'Reset',
        hasNoData: 'No data.',
        itemName: 'Item Name',
        lotNo: 'Lot No.',
        inventClass: 'Inventory Class',
        inventClass1: 'Original fabric',
        inventClass2: 'Semi product',
        inventClass3: 'Prototype',
        weight: 'weight',
        coreNo: 'Core No.',
        location: 'Location',
        rollLength: 'Length',
        rollWidth: 'Width',
        rollThickness: 'Thickness',
        rollWeight: 'Weight',
        usage: 'Usage'
    },
    'cn': {
        currentLang: 'zh',
        name: '名称',
        phone: '电话',
        gender: '性别',
        email: '电子邮件',
        homepage: '主页',
        footer: '这是页脚区。',
        navigator: '这是导航区。',
        lookupName: '名称',
        lookupPhone: '电话',
        lookupGender: '性别',
        male: '男',
        female: '女',
        other: '其他',
        all: '所有',
        birthday: '生日',
        province: '省',
        search: '搜索',
        reset: '重啟',
        hasNoData: '沒有數據。',
        itemName: 'Item Name',
        lotNo: 'Lot No.',
        inventClass: 'Inventory Class',
        inventClass1: 'Original fabric',
        inventClass2: 'Semi product',
        inventClass3: 'Prototype',
        weight: 'weight',
        coreNo: 'Core No.',
        location: 'Location',
        rollLength: 'Length',
        rollWidth: 'Width',
        rollThickness: 'Thickness',
        rollWeight: 'Weight',
        usage: 'Usage'
    },
    'vn': {
        currentLang: 'vn',
        name: 'Tên',
        phone: 'Điện thoại',
        gender: 'Giới tính',
        email: 'Email',
        homepage: 'Trang chủ',
        footer: 'Đây là đáy trang.',
        navigator: 'Đây là khu vực menu.',
        lookupName: 'Tên',
        lookupPhone: 'Điện thoại',
        lookupGender: 'Giới tính',
        male: 'Nam',
        female: 'Nữ',
        other: 'Khác',
        all: 'Tất cả',
        birthday: 'Ngày sinh',
        province: 'Tỉnh',
        search: 'Tìm',
        reset: 'Cài lại',
        hasNoData: 'Không có dữ liệu.',
        itemName: 'Tên hàng',
        lotNo: 'Số lô',
        inventClass: 'Phân loại',
        inventClass1: 'Nguyên liệu thô',
        inventClass2: 'Bán Thành phẩm',
        inventClass3: 'Nguyên mẫu',
        weight: 'Cân nặng',
        coreNo: 'Core No.',
        location: 'Vị trí',
        rollLength: 'Dài',
        rollWidth: 'Rộng',
        rollThickness: 'Dày',
        rollWeight: 'Nặng',
        usage: 'Sử dụng'
    },
    'es': {
        currentLang: 'es',
        name: 'Nombre',
        phone: 'Teléfono',
        gender: 'Género',
        email: 'Correo electrónico',
        homepage: 'Página principal',
        footer: 'Esta es la zona de pie de página.',
        navigator: 'Esta es la zona del navegador.',
        lookupName: 'Nombre',
        lookupPhone: 'Teléfono',
        lookupGender: 'Género',
        male: 'Masculina',
        female: 'Hembra',
        other: 'Otra',
        all: 'todas',
        birthday: 'Cumpleaños',
        province: 'Provincia',
        search: 'buscar',
        reset: 'Reiniciar',
        hasNoData: 'Sin datos.',
        itemName: 'Item Name',
        lotNo: 'Lot No.',
        inventClass: 'Inventory Class',
        inventClass1: 'Original fabric',
        inventClass2: 'Semi product',
        inventClass3: 'Prototype',
        weight: 'weight',
        coreNo: 'Core No.',
        location: 'Location',
        rollLength: 'Length',
        rollWidth: 'Width',
        rollThickness: 'Thickness',
        rollWeight: 'Weight',
        usage: 'Usage'
    }
};

const i18n = new VueI18n({
    locale: 'jp', // set locale
    fallbackLocale: 'en', // set fallback locale
    messages, // set locale messages
});

export default i18n;